#!/usr/bin/env python3
"""Generate the embedded 16x16 Chinese glyph subset from GNU Unifont."""

import argparse
from pathlib import Path


def collect_codepoints(paths):
    codepoints = set()
    for path in paths:
        candidates = path.rglob("*") if path.is_dir() else (path,)
        for candidate in candidates:
            if candidate.suffix not in {".c", ".h"}:
                continue
            text = candidate.read_text(encoding="utf-8")
            codepoints.update(
                ord(char) for char in text if "\u3400" <= char <= "\u9fff"
            )
    return sorted(codepoints)


def load_unifont(path, wanted):
    glyphs = {}
    with path.open(encoding="ascii") as source:
        for line in source:
            codepoint_text, separator, bitmap = line.strip().partition(":")
            if not separator:
                continue
            codepoint = int(codepoint_text, 16)
            if codepoint in wanted and len(bitmap) == 64:
                glyphs[codepoint] = bytes.fromhex(bitmap)
    return glyphs


def format_values(values, width, per_line):
    rows = []
    for offset in range(0, len(values), per_line):
        chunk = values[offset : offset + per_line]
        rows.append("\t" + ", ".join(f"0x{value:0{width}X}" for value in chunk))
    return ",\n".join(rows)


def write_output(path, codepoints, glyphs):
    missing = [codepoint for codepoint in codepoints if codepoint not in glyphs]
    if missing:
        formatted = ", ".join(f"U+{codepoint:04X}" for codepoint in missing)
        raise SystemExit(f"Missing 16x16 glyphs: {formatted}")

    lines = [
        "/* Generated by tools/fontgen/fontgen.py from GNU Unifont. */",
        "/* Font glyphs are licensed under SIL Open Font License 1.1. */",
        "",
        f"#define GFX_FONT_ZH_GLYPH_COUNT {len(codepoints)}",
        "",
        "static const u16 _gfx_font_zh_codepoints[] = {",
        format_values(codepoints, 4, 8),
        "};",
        "",
        "static const u8 _gfx_font_zh_glyphs[][32] = {",
    ]
    for codepoint in codepoints:
        lines.append(f"\t/* U+{codepoint:04X} */ {{")
        lines.append(format_values(glyphs[codepoint], 2, 16))
        lines.append("\t},")
    lines.extend(("};", ""))
    path.write_text("\n".join(lines), encoding="ascii")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True, type=Path, help="GNU Unifont .hex file")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--max-glyphs", type=int, default=256)
    parser.add_argument("sources", nargs="+", type=Path)
    args = parser.parse_args()

    codepoints = collect_codepoints(args.sources)
    if len(codepoints) > args.max_glyphs:
        raise SystemExit(
            f"Chinese glyph count {len(codepoints)} exceeds limit {args.max_glyphs}"
        )
    glyphs = load_unifont(args.font, set(codepoints))
    write_output(args.output, codepoints, glyphs)
    print(f"Generated {len(codepoints)} glyphs in {args.output}")


if __name__ == "__main__":
    main()
